### ISSUE TITLE
Automatisches Update

### ISSUE THREAD

**Issue by sbr1nkmann** [tegosGroup/NAVToGit#2]
Beim Starten des Tools sollte geprüft werden, ob eine neue Version verfügbar ist.
Der User sollte gefragt werden, ob er auf diese Updaten möchte.
Wird diese Frage mit "Ja" bestätigt, so wird das Update durchgeführt.

**Comment by Pixelstrudel** [comment]
Vielleicht kann man dafür ja eine Importfunktion [wie diese hier](https://dfinke.github.io/powershell/2016/11/21/Quickly-Install-PowerShell-Modules-from-GitHub.html) verwenden 😉
