### ISSUE TITLE
Show third party areas as filter strings for manual fob export (2009)

### ISSUE THREAD

**Issue by Pixelstrudel** [tegosGroup/NAVToGit#24]
As the third party fob export does not work for NAV 2009 the user could at least get a message showing the filter strings (and file names) which have to be exported manually and allowing to easily copy it into C/SIDE.

For example:
> Following third-party areas have to be exported manually:
> 
> EXAMPLE.fob 500000..510000
> EXAMPLE2.fob 600000..610000
> [...]

**Comment by swortmann** [comment]
Added in Release v0.2.8
