### ISSUE TITLE
Selective Export does not work with Dataports and Forms

### ISSUE THREAD

**Issue by Pixelstrudel** [tegosGroup/NAVToGit#25]
See title.

When entering a filter for forms and dataports in Selective Export these object types are ignored and not exported

**Comment by swortmann** [comment]
Fixed with commit [e757f457dd30c948f90529df9efb5c8e58e7d2d4](https://github.com/tegosGroup/NAVToGit/commit/e757f457dd30c948f90529df9efb5c8e58e7d2d4)
