### ISSUE TITLE
Selective Import

### ISSUE THREAD

**Issue by DrAldenteDDL** [tegosGroup/NAVToGit#32]
Beim Importieren wäre die Möglichkeit eines selektiven Imports gut.
Ähnlich zum export.

**Comment by NVardanyan** [comment]
Beim Importieren vergleicht das Modul die „Textversion“ der lokalen NAV Datenbank mit der vorhandenen Version im Git Repository. So ist es möglich, nach dem Vergleich, dass der Anwender die Unterschiede zwischen Objektversionen selbst begutachten und sich ggf. nur für eine Auswahl an Objekten entscheiden kann.Also gibt es Möglichkeit schön nur selektierte Objekte importieren(More Infos im Tegopedia).Da im Git befindet sich das aktuellste Version,Anwender kann ohne vergleich nicht wissen welche Objekte von andere Anwender im Moment geändert sind.

**Comment by DrAldenteDDL** [comment]
Mir ging es darum die möglichkeit zu haben ohne einen vergleich ein Objekt zu importieren.
Als ein neues zusätzliches feature.
Zum Beispiel weis ich das die Tabelle 5030452 unterschiedlich ist zu der Version in meiner Datenbank.
Ich weis das es sonst keine anderen Änderungen gibt.
Ich möchte nicht alle Objekte vergleichen um dann zu erfahren, dass die Tabelle 5030452 unterschiedlich ist.
Ich hätte gerne die Möglichkeit ähnlich zum export sagen zu können importiere mir Tabelle 5030452 in meine Datenbank.

Das sollte eine Anfrage zu einem neuen feature sein evtl. ist das nicht ganz klar geworden.

**Comment by swortmann** [comment]
Gute Idee, das kann den Importvorgang bei kleinen Änderungen deutlich beschleunigen - auch wenn dieses Feature natürlich, wie auch der selektive Export, immer mit großer Vorsicht zu genießen ist ;)
Wir werden diese Funktion wohl in Anlehnung an den selektiven Export integrieren, d.h. mit Filtermöglichkeit im CLI und GUI.

**Comment by swortmann** [comment]
Feature wurde in Release v0.3.0 integriert.
Update der lokalen Installation erfolgt entweder nach einiger Zeit automatisch, oder direkt manuell per `Update-NavToGit`
