### ISSUE TITLE
ThirdPartyIdAreas pro Repository

### ISSUE THREAD

**Issue by Pixelstrudel** [tegosGroup/NAVToGit#4]
Die ThirdPartyIdAreas werden zwar oft einheitlich und repoübergreifend gültig sein, dennoch wäre es wünschenswert für Ausnahmen andere Bereiche konfigurieren zu können.

Ideal wäre es daher, wenn die ThirdPartyIdAreas.json aus dem konfigurierten Repoordner eingelesen wird. So kann diese auch über die Versionskontrolle mit jedem Entwickler geteilt werden.

Vielleicht kann die unter %appdata% vorhandene ThirdPartyIdAreas.json als Fallback genutzt werden, falls im Repoordner keine Datei abgelegt wurde.

Damit die ThirdPartyIdAreas.json nicht durch den Objektexport gelöscht wird, muss zuvor der Issue #3 bearbeitet werden.

**Comment by nbuko** [comment]
Done.
