### ISSUE TITLE
The input line is too long

### ISSUE THREAD

**Issue by chpies** [tegosGroup/NAVToGit#51]
When you add too many entries in the ThirdPartyIdAreas.json and try to import from git into the database you get lots of error-windows saying that the input line is too long.

![Screenshot 2023-03-23 111024](https://user-images.githubusercontent.com/128693458/227171354-ceddb733-1df9-49a1-b349-d78f79a2cf67.png)

After a look into the codebase its most likely a problem with the Start-Export function and not directly a problem with the import of the json file.

**Comment by swortmann** [comment]
#60
