### ISSUE TITLE
Error with temporary fin.zup during Export/Import

### ISSUE THREAD

**Issue by swortmann** [tegosGroup/NAVToGit#6]
During export/import an error is thrown regarding the temporary created fin.zup.

We could **not** recreate this bug yet - if you have encountered the same problem, leave a comment!

**Comment by Pixelstrudel** [comment]
I got this error once and apparently the finsql.exe was trying to create the file when it already existed.

If you can't find the exact issue why not try removing the .zup file after being used by the functions? 

After all it's supposed to be temporary and isn't used again anyway 😎👍

**Comment by swortmann** [comment]
Commit [9328737](https://github.com/tegosGroup/NAVToGit/commit/932873760cf38795b03a7eea326689ada66f3929) implemented different zup filenames for every finsql process during export. After the function is complete, all zup files are being deleted. 😃 

Issue should be fixed and is now closed.
